data <- read.csv(file.choose())
View(data)
str(data)
data$gender_fac <- as.factor(data$gender)
str(data)
data$gender_fac <- factor(data$gender_fac, levels = c("Male", "Female"))
levels(data$gender_fac)
data$diagnosis_fac <- as.factor(data$diagnosis)
str(data)
data$diagnosis_fac <- factor(data$diagnosis_fac, levels = c("Cancer", "Normal"))
levels(data$diagnosis_fac)
data$smoker_fac <- as.factor(data$smoker)
str(data)
data$smoker_fac <- factor(data$smoker_fac, levels = c("Yes", "No"))
levels(data$smoker_fac)
data$smoker_num <- ifelse(data$smoker_fac == "Yes", 1,0)
class(data$smoker_num)
data$smoker_num <- as.factor(data$smoker_num)
class(data$smoker_num)
write.csv(data, file = "clean_data/patient_info_clean.csv")
save.image(file = "full_workspace.RData")
